/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as ImoveisIdRouteImport } from './routes/imoveis.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIdRoute = ImoveisIdRouteImport.update({
  id: '/imoveis/$id',
  path: '/imoveis/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/imoveis/': typeof ImoveisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/imoveis': typeof ImoveisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/imoveis/$id': typeof ImoveisIdRoute
  '/imoveis/': typeof ImoveisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/imoveis/$id' | '/imoveis/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/imoveis/$id' | '/imoveis'
  id: '__root__' | '/' | '/imoveis/$id' | '/imoveis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImoveisIdRoute: typeof ImoveisIdRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/imoveis'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/$id': {
      id: '/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof ImoveisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImoveisIdRoute: ImoveisIdRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
